### ISSUE TITLE
Deleting layers with clipping masks causes plugin to crash

### ISSUE THREAD

**Issue by kylearichard** [abynim/sketch-tweaks#1]
I noticed that when I have the indent guide tweak turned on, removing layers with clipping masks (either via delete or dragging to a new artboard) causes Sketch to fail. I reproduced this issue consistently until I disabled Sketch Tweaks, then things returned to normal.

**Comment by abynim** [comment]
Thanks for reporting @kylearichard. I can reproduce this. Will fix.

**Comment by abynim** [comment]
This should be fixed in v1.1. Please add a comment if you're still running into this and I'll reopen the Issue. Thanks again for reporting!
